name: null
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.3
  - astroid=2.4.1
  - attrs=19.3.0
  - autoflake=1.3
  - backcall=0.1.0
  - black=19.10b0
  - bleach=3.1.5
  - brotlipy=0.7.0
  - ca-certificates=2020.4.5.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - cryptography=2.9.2
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - ete3=3.1.1
  - expat=2.2.9
  - fontconfig=2.13.1
  - freetype=2.10.2
  - gettext=0.19.8.1
  - glib=2.64.2
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - icu=64.2
  - idna=2.9
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0
  - ipykernel=5.2.1
  - ipython=7.14.0
  - ipython_genutils=0.2.0
  - isort=4.3.21
  - jedi=0.17.0
  - jinja2=2.11.2
  - joblib=0.15.1
  - jpeg=9c
  - json5=0.9.0
  - jsonschema=3.2.0
  - jupyter_client=6.1.3
  - jupyter_core=4.6.3
  - jupyterlab=2.1.2
  - jupyterlab_server=1.1.4
  - kiwisolver=1.2.0
  - lazy-object-proxy=1.4.3
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.5.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libopenblas=0.3.9
  - libpng=1.6.37
  - libsodium=1.0.17
  - libstdcxx-ng=9.2.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxkbcommon=0.10.0
  - libxml2=2.9.10
  - libxslt=1.1.33
  - llvm-openmp=10.0.0
  - lxml=4.5.1
  - markupsafe=1.1.1
  - matplotlib=3.2.1
  - matplotlib-base=3.2.1
  - mccabe=0.6.1
  - mistune=0.8.4
  - mypy_extensions=0.4.3
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ncurses=6.1
  - notebook=6.0.3
  - nspr=4.25
  - nss=3.47
  - numpy=1.18.4
  - openssl=1.1.1g
  - packaging=20.1
  - pandas=1.0.3
  - pandoc=2.9.2.1
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pathspec=0.8.0
  - patsy=0.5.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.1
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.5
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pyflakes=2.2.0
  - pygments=2.6.1
  - pylint=2.5.2
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - python-dotenv=0.13.0
  - python_abi=3.7
  - pytz=2020.1
  - pyzmq=19.0.1
  - qt=5.12.5
  - readline=8.0
  - regex=2020.5.14
  - requests=2.23.0
  - scikit-learn=0.23.0
  - scipy=1.4.1
  - seaborn=0.10.1
  - send2trash=1.5.0
  - setuptools=46.4.0
  - six=1.14.0
  - sqlite=3.30.1
  - statsmodels=0.11.1
  - terminado=0.8.3
  - testpath=0.4.4
  - threadpoolctl=2.0.0
  - tk=8.6.10
  - toml=0.10.1
  - tornado=6.0.4
  - traitlets=4.3.3
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.2
  - urllib3=1.25.9
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - wrapt=1.11.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - pip:
    - brotli==1.0.7
    - dash==1.12.0
    - dash-core-components==1.10.0
    - dash-cytoscape==0.1.1
    - dash-html-components==1.0.3
    - dash-renderer==1.4.1
    - dash-table==4.7.0
    - dill==0.3.1.1
    - flask==1.1.2
    - flask-compress==1.5.0
    - future==0.18.2
    - gevent==20.5.0
    - greenlet==0.4.15
    - imagecodecs==2020.2.18
    - imageio==2.8.0
    - interpret==0.1.22
    - interpret-core==0.1.22
    - itsdangerous==1.1.0
    - lime==0.2.0.0
    - networkx==2.4
    - pillow==5.4.1
    - plotly==4.7.1
    - psutil==5.7.0
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - pywavelets==1.1.1
    - retrying==1.3.3
    - salib==1.3.11
    - scikit-image==0.17.2
    - shap==0.35.0
    - tifffile==2020.5.11
    - tqdm==4.46.0
    - treeinterpreter==0.2.2
    - werkzeug==1.0.1

